<?php
        
        $content1 = '
<section class="landing-block g-pb-80 js-animation animation-none g-pt-50" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
	<div class="landing-block-node-container container js-animation fadeIn" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
		<div class="landing-block-node-header u-heading-v2-4--bottom g-brd-primary g-mb-40">
			<h2 class="landing-block-node-title text-uppercase h1 u-heading-v2__title g-line-height-1_3 g-font-weight-600 g-mb-minus-10 g-text-break-word g-font-size-33">'.$vars['block_1_header'].'</h2>
		</div>

		<div class="landing-block-node-text g-font-size-16">'.$vars['block_1_text'].'</div>
    
    </div>
</section>
        ';
        
        
        $content2 = '
<section class="landing-block js-animation g-pt-20 g-pb-20 g-bg-gray-light-v5 animation-none" style="animation-duration: 1000ms; visibility: hidden; animation-name: none; animation-play-state: paused;">
        <div class="container">
            <div class="landing-block-node-inner text-uppercase text-center u-heading-v2-4--bottom g-brd-primary">
                <h4 class="landing-block-node-subtitle h6 g-font-weight-800 g-font-size-12 g-letter-spacing-1 g-color-primary g-mb-20">'.$vars['block_2_subheader'].'</h4>
                <h2 class="landing-block-node-title h1 u-heading-v2__title g-line-height-1_3 g-font-weight-600 g-mb-minus-10 g-font-size-30">'.$vars['block_2_header'].'</h2>
            </div>
        </div>
</section>
        ';
        
        
        $content3 = '<section class="landing-block g-pl-0 g-pr-0 g-bg-white g-pb-100 g-pt-50">'.htmlspecialchars_decode(trim($vars['block_3_html'])).'</section>';
        

        $content4 = '
<section class="landing-block g-bg-gray-light-v5 g-pt-40 g-pb-40">
	<div class="container">
		<div class="landing-block-node-container row g-flex-centered align-items-end">
			<div class="landing-block-node-button-container text-left col-4 js-animation slideInLeft" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
				<a class="landing-block-node-button landing-semantic-link-image-medium btn btn-sm text-uppercase u-btn-primary rounded-0 g-px-15 font-weight-bold g-mb-0 g-brd-10" href="'.$vars['block_4_link'].'" target="_self">'.$vars['block_4_button'].'</a>
			</div>
			<div class="landing-block-node-text-container text-right col-8 js-animation slideInRight" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
				<h6 class="landing-block-node-title landing-semantic-text-medium h6 g-mb-0 font-weight-bold">'.$vars['block_4_header'].'</h6>
				<div class="landing-block-node-text landing-semantic-text-small g-font-size-14">'.$vars['block_4_text'].'</div>
			</div>
		</div>
	</div>
</section>
        ';
/*
        $content4 = '
<section class="landing-block g-bg-gray-light-v5 g-pt-40 g-pb-40">
	<div class="container">
		<div class="landing-block-node-container row g-flex-centered align-items-end">
			<div class="landing-block-node-button-container text-left col-4 js-animation slideInLeft" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
				<a class="landing-block-node-button landing-semantic-link-image-medium btn btn-sm text-uppercase u-btn-primary rounded-0 g-px-15 font-weight-bold g-mb-0 g-brd-10" href="'.$vars[block_4_link].'" target="_popup">'.$vars[block_4_button].'</a>
			</div>
			<div class="landing-block-node-text-container text-right col-8 js-animation slideInRight" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
				<h6 class="landing-block-node-title landing-semantic-text-medium h6 g-mb-0 font-weight-bold">'.$vars[block_4_header].'</h6>
				<div class="landing-block-node-text landing-semantic-text-small g-font-size-14">'.$vars[block_4_text].'</div>
			</div>
		</div>
	</div>
</section>
        ';
        
*/




        
        $content5 = '
<section class="landing-block landing-semantic-background-color js-animation g-pb-20 g-bg-main animation-none g-pt-100 animated" style="animation-duration: 1000ms; animation-play-state: running;">

	<div class="container text-center g-max-width-800">

		<div class="landing-block-node-inner text-uppercase u-heading-v2-4--bottom g-brd-primary">
			<h4 class="landing-block-node-subtitle landing-semantic-subtitle-medium-primary font-weight-bold g-font-size-12 g-color-primary g-mb-15">'.$vars['block_5_subheader'].'</h4>
			<h2 class="landing-block-node-title landing-semantic-title-medium u-heading-v2__title g-line-height-1_1 font-weight-bold g-font-size-40 g-color-black g-mb-minus-10">'.$vars['block_5_header'].'</h2>
		</div>

		<div class="landing-block-node-text landing-semantic-text-medium g-pb-1 g-mb-auto g-color-main">'.$vars['block_5_text'].'</div>
	</div>

</section>
        ';
        
        
        $content6 = '
<section class="landing-block g-pb-100 g-pt-20">
	<div class="container">
		<div class="row landing-block-inner"><div class="landing-block-card js-animation fadeIn col-lg-6 g-mb-40 g-mb-0--lg" style="animation-duration: 1000ms; visibility: hidden; animation-name: none; animation-play-state: paused;">
				<div class="landing-block-card-header text-uppercase u-heading-v2-4--bottom g-brd-primary g-mb-40">
					<h4 class="landing-block-node-subtitle landing-semantic-subtitle-small h6 font-weight-bold g-font-size-12 g-letter-spacing-1 g-color-primary g-mb-20"> </h4>
					<h2 class="landing-block-node-title landing-semantic-title-medium h1 u-heading-v2__title g-line-height-1_3 font-weight-bold g-text-break-word g-font-size-35 g-mb-minus-10">'.$vars['block_6_header_1'].'</h2>
				</div>

				<div class="landing-block-node-text landing-semantic-text-medium g-mb-50"><p>'.$vars['block_6_text_1'].'</p></div>
			</div><div class="landing-block-card js-animation fadeIn col-lg-6 g-mb-40 g-mb-0--lg" style="animation-duration: 1000ms; visibility: hidden; animation-name: none; animation-play-state: paused;">
				<div class="landing-block-card-header text-uppercase u-heading-v2-4--bottom g-brd-primary g-mb-40">
					<h4 class="landing-block-node-subtitle landing-semantic-subtitle-small h6 font-weight-bold g-font-size-12 g-letter-spacing-1 g-color-primary g-mb-20"> </h4>
					<h2 class="landing-block-node-title landing-semantic-title-medium h1 u-heading-v2__title g-line-height-1_3 font-weight-bold g-text-break-word g-font-size-35 g-mb-minus-10">'.$vars['block_6_header_2'].'</h2>
				</div>

				<div class="landing-block-node-text landing-semantic-text-medium g-mb-50"><p>'.$vars['block_6_text_2'].'</p></div>
			</div><div class="landing-block-card js-animation fadeIn col-lg-6 g-mb-40 g-mb-0--lg" style="animation-duration: 1000ms; visibility: hidden; animation-name: none; animation-play-state: paused;">
				<div class="landing-block-card-header text-uppercase u-heading-v2-4--bottom g-brd-primary g-mb-40">
					<h4 class="landing-block-node-subtitle landing-semantic-subtitle-small h6 font-weight-bold g-font-size-12 g-letter-spacing-1 g-color-primary g-mb-20"> </h4>
					<h2 class="landing-block-node-title landing-semantic-title-medium h1 u-heading-v2__title g-line-height-1_3 font-weight-bold g-text-break-word g-font-size-35 g-mb-minus-10">'.$vars['block_6_header_3'].'</h2>
				</div>

				<div class="landing-block-node-text landing-semantic-text-medium g-mb-50"><p>'.$vars['block_6_text_3'].'</p></div>
			</div><div class="landing-block-card js-animation fadeIn col-lg-6 g-mb-40 g-mb-0--lg" style="animation-duration: 1000ms; visibility: hidden; animation-name: none; animation-play-state: paused;">
				<div class="landing-block-card-header text-uppercase u-heading-v2-4--bottom g-brd-primary g-mb-40">
					<h4 class="landing-block-node-subtitle landing-semantic-subtitle-small h6 font-weight-bold g-font-size-12 g-letter-spacing-1 g-color-primary g-mb-20"> </h4>
					<h2 class="landing-block-node-title landing-semantic-title-medium h1 u-heading-v2__title g-line-height-1_3 font-weight-bold g-text-break-word g-font-size-35 g-mb-minus-10">'.$vars['block_6_header_4'].'</h2>
				</div>

				<div class="landing-block-node-text landing-semantic-text-medium g-mb-50"><p>'.$vars['block_6_text_4'].'</p></div>
			</div></div>
	</div>
</section>
        ';
        
        $content7 = '
<section class="landing-block g-pt-10 g-pb-10">

        <hr class="landing-block-line landing-semantic-border my-0 g-brd-gray-dark-v1">

</section>
        ';
        


/*
        $content8 = '
<section class="g-pos-rel landing-block text-center g-pb-100 g-pt-100">

	<div class="container">

		<div class="landing-block-form-styles" hidden="">
			<div class="g-bg-transparent h1 g-color-white g-brd-none g-pa-0" data-form-style-wrapper-padding="1" data-form-style-bg="1" data-form-style-bg-content="1" data-form-style-bg-block="1" data-form-style-header-font-size="1" data-form-style-main-font-weight="1" data-form-style-button-font-color="1" data-form-style-border-block="1">
			</div>
			<div class="g-bg-primary g-color-primary g-brd-primary" data-form-style-main-bg="1" data-form-style-main-border-color="1" data-form-style-main-font-color-hover="1">
			</div>
			<div class="g-bg-gray-light-v5 g-color-gray-dark-v1 g-brd-around g-brd-white rounded-0" data-form-style-input-bg="1" data-form-style-input-select-bg="1" data-form-style-input-border="1" data-form-style-input-border-radius="1" data-form-style-main-font-color="1">
			</div>
			<div class="g-brd-around g-brd-gray-light-v2 g-color-gray-dark-v5 g-bg-black-opacity-0_7" data-form-style-input-border-color="1" data-form-style-input-border-hover="1" data-form-style-icon-font-color="1">
			</div>


			<!--			for resource booking-->
			<div class="g-bg-gray-dark-v5" data-form-style-bg-as-text="1">
			</div>

			<div class="g-bg-gray-light-v5" data-form-style-input-bg-light="1">
			</div>

			<div class="g-bg-gray-light-v4" data-form-style-input-bg-light2="1">
			</div>

			<div class="g-bg-primary-opacity-0_4" data-form-style-main-bg-light="1">
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 order-2 order-md-1">
				<div class="bitrix24forms g-brd-white-opacity-0_6 u-form-alert-v4" data-b24form="39|pnrr4o" data-b24form-use-style="Y" data-b24form-show-header="N" data-b24form-original-domain="https://movens.bitrix24.ru"><iframe id="bx_form_iframe_39" name="bx_form_iframe_39" src="https://movens.bitrix24.ru/pub/form.php?view=frame&amp;form_id=39&amp;widget_user_lang=ru&amp;sec=pnrr4o&amp;r=1594290725218#%7B%22domain%22%3A%22https%3A%2F%2Fevent.movens.ru%22%2C%22from%22%3A%22https%3A%2F%2Fevent.movens.ru%2Fpreview%2F3bd0ccae227cd9dc80b53f2f313e11b5%2Ftickets%2Fbilety-na-poezd-002y-moskva-kazan%2F%22%2C%22options%22%3A%7B%7D%7D" scrolling="no" frameborder="0" marginheight="0" marginwidth="0" style="width: 100%; height: 911px; border: 0px; overflow: hidden; padding: 0px; margin: 0px;"></iframe></div>
			</div>

			<div class="col-md-6 order-1 order-md-2">
				<div class="text-center g-overflow-hidden">
					<h3 class="landing-block-node-main-title h3 text-uppercase g-font-weight-700 g-color-black text-left g-mb-10 g-font-size-20">'.$vars[block_7_header].'</h3>

					<div class="landing-block-node-text g-line-height-1_5 text-left g-mb-40 g-color-gray-dark-v5" data-form-style-main-font-family="1" data-form-style-main-font-weight="1" data-form-style-header-text-font-size="1"><p>'.$vars[block_7_text].'</p></div>
					<div class="g-mx-minus-2 g-my-minus-2">
						<div class="row mx-0"><div class="landing-block-card-contact js-animation fadeIn col-sm-6 g-brd-left g-brd-bottom g-brd-gray-light-v4 g-px-15 g-py-25 landing-card" data-card-preset="link" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
								<a href="tel:+74954142242" class="landing-block-card-linkcontact-link g-text-decoration-none--hover" target="_self">
									<span class="landing-block-card-contact-icon-container g-color-primary g-line-height-1 d-inline-block g-font-size-50 g-mb-30">
										<i class="landing-block-card-linkcontact-icon icon-call-in" data-pseudo-url="{&quot;text&quot;:&quot;&quot;,&quot;href&quot;:&quot;&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;enabled&quot;:false}"></i>
									</span>
									<span class="landing-block-card-linkcontact-title h3 d-block text-uppercase g-font-size-11 g-color-gray-dark-v5 mb-0" data-form-style-label-font-weight="1" data-form-style-label-font-size="1" data-form-style-second-font-color="1">Телефон</span>
									<span class="landing-block-card-linkcontact-text g-text-decoration-none g-text-underline--hover g-font-weight-700 g-color-gray-dark-v1 g-font-size-15">+7 495 414 22 42 доб. 103</span>
								</a>
							</div><div class="landing-block-card-contact js-animation fadeIn col-sm-6 g-brd-left g-brd-bottom g-brd-gray-light-v4 g-px-15 g-py-25 landing-card" data-card-preset="link" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
								<a href="mailto:tickets@movens.ru" class="landing-block-card-linkcontact-link g-text-decoration-none--hover" target="_self">
									<span class="landing-block-card-contact-icon-container g-color-primary g-line-height-1 d-inline-block g-font-size-50 g-mb-30">
										<i class="landing-block-card-linkcontact-icon icon-line icon-envelope-letter" data-pseudo-url="{&quot;text&quot;:&quot;&quot;,&quot;href&quot;:&quot;&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;enabled&quot;:false}"></i>
									</span>
									<span class="landing-block-card-linkcontact-title h3 d-block text-uppercase g-font-size-11 g-color-gray-dark-v5 mb-0" data-form-style-label-font-weight="1" data-form-style-label-font-size="1" data-form-style-second-font-color="1">Почта</span>
									<span class="landing-block-card-linkcontact-text g-text-decoration-none g-text-underline--hover g-font-weight-700 g-color-gray-dark-v1 g-font-size-15">tickets@movens.ru</span>
								</a>
							</div></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
        ';
*/


/*
        $content8 = '
<section class="g-pos-rel landing-block text-center g-pb-100 g-pt-100">

	<div class="container">

		<div class="landing-block-form-styles" hidden="">
			<div class="g-bg-transparent h1 g-color-white g-brd-none g-pa-0" data-form-style-wrapper-padding="1" data-form-style-bg="1" data-form-style-bg-content="1" data-form-style-bg-block="1" data-form-style-header-font-size="1" data-form-style-main-font-weight="1" data-form-style-button-font-color="1" data-form-style-border-block="1">
			</div>
			<div class="g-bg-primary g-color-primary g-brd-primary" data-form-style-main-bg="1" data-form-style-main-border-color="1" data-form-style-main-font-color-hover="1">
			</div>
			<div class="g-bg-gray-light-v5 g-color-gray-dark-v1 g-brd-around g-brd-white rounded-0" data-form-style-input-bg="1" data-form-style-input-select-bg="1" data-form-style-input-border="1" data-form-style-input-border-radius="1" data-form-style-main-font-color="1">
			</div>
			<div class="g-brd-around g-brd-gray-light-v2 g-color-gray-dark-v5 g-bg-black-opacity-0_7" data-form-style-input-border-color="1" data-form-style-input-border-hover="1" data-form-style-icon-font-color="1">
			</div>


			<!--			for resource booking-->
			<div class="g-bg-gray-dark-v5" data-form-style-bg-as-text="1">
			</div>

			<div class="g-bg-gray-light-v5" data-form-style-input-bg-light="1">
			</div>

			<div class="g-bg-gray-light-v4" data-form-style-input-bg-light2="1">
			</div>

			<div class="g-bg-primary-opacity-0_4" data-form-style-main-bg-light="1">
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 order-2 order-md-1">
				<div class="bitrix24forms g-brd-white-opacity-0_6 u-form-alert-v4" data-b24form="37|bvr7kg" data-b24form-use-style="Y" data-b24form-show-header="N" data-b24form-original-domain="https://movens.bitrix24.ru"><iframe id="bx_form_iframe_37" name="bx_form_iframe_37" src="https://movens.bitrix24.ru/pub/form.php?view=frame&amp;form_id=37&amp;widget_user_lang=ru&amp;sec=bvr7kg&amp;r=1596209852426#%7B%22domain%22%3A%22https%3A%2F%2Fevent.movens.ru%22%2C%22from%22%3A%22https%3A%2F%2Fevent.movens.ru%2Ftickets%2Fbilety-na-poezd-016a-moskva-murmansk8%2F%22%2C%22options%22%3A%7B%7D%7D" scrolling="no" frameborder="0" marginheight="0" marginwidth="0" style="width: 100%; height: 917px; border: 0px; overflow: hidden; padding: 0px; margin: 0px;"></iframe></div>
			</div>

			<div class="col-md-6 order-1 order-md-2">
				<div class="text-center g-overflow-hidden">
					<h3 class="landing-block-node-main-title h3 text-uppercase g-font-weight-700 g-color-black text-left g-mb-10 g-font-size-20">'.$vars[block_7_header].'</h3>

					<div class="landing-block-node-text g-line-height-1_5 text-left g-mb-40 g-color-gray-dark-v5" data-form-style-main-font-family="1" data-form-style-main-font-weight="1" data-form-style-header-text-font-size="1"><p>'.$vars[block_7_text].'</p></div>
					<div class="g-mx-minus-2 g-my-minus-2">
						<div class="row mx-0"><div class="landing-block-card-contact js-animation fadeIn col-sm-6 g-brd-left g-brd-bottom g-brd-gray-light-v4 g-px-15 g-py-25 landing-card" data-card-preset="link" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
								<a href="tel:+74954142242" class="landing-block-card-linkcontact-link g-text-decoration-none--hover" target="_self">
									<span class="landing-block-card-contact-icon-container g-color-primary g-line-height-1 d-inline-block g-font-size-50 g-mb-30">
										<i class="landing-block-card-linkcontact-icon icon-call-in" data-pseudo-url="{&quot;text&quot;:&quot;&quot;,&quot;href&quot;:&quot;&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;enabled&quot;:false}"></i>
									</span>
									<span class="landing-block-card-linkcontact-title h3 d-block text-uppercase g-font-size-11 g-color-gray-dark-v5 mb-0" data-form-style-label-font-weight="1" data-form-style-label-font-size="1" data-form-style-second-font-color="1">Телефон</span>
									<span class="landing-block-card-linkcontact-text g-text-decoration-none g-text-underline--hover g-font-weight-700 g-color-gray-dark-v1 g-font-size-15">+7 495 414 22 42 доб. 103</span>
								</a>
							</div><div class="landing-block-card-contact js-animation fadeIn col-sm-6 g-brd-left g-brd-bottom g-brd-gray-light-v4 g-px-15 g-py-25 landing-card" data-card-preset="link" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
								<a href="mailto:tickets@movens.ru" class="landing-block-card-linkcontact-link g-text-decoration-none--hover" target="_self">
									<span class="landing-block-card-contact-icon-container g-color-primary g-line-height-1 d-inline-block g-font-size-50 g-mb-30">
										<i class="landing-block-card-linkcontact-icon icon-line icon-envelope-letter" data-pseudo-url="{&quot;text&quot;:&quot;&quot;,&quot;href&quot;:&quot;&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;enabled&quot;:false}"></i>
									</span>
									<span class="landing-block-card-linkcontact-title h3 d-block text-uppercase g-font-size-11 g-color-gray-dark-v5 mb-0" data-form-style-label-font-weight="1" data-form-style-label-font-size="1" data-form-style-second-font-color="1">Почта</span>
									<span class="landing-block-card-linkcontact-text g-text-decoration-none g-text-underline--hover g-font-weight-700 g-color-gray-dark-v1 g-font-size-15">tickets@movens.ru</span>
								</a>
							</div></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
        ';
*/


        $content8 = '
<section class="g-pos-rel landing-block text-center g-pb-100 g-pt-100">

	<div class="container">

		<div class="landing-block-form-styles" hidden="">
			<div class="g-bg-transparent h1 g-color-white g-brd-none g-pa-0" data-form-style-wrapper-padding="1" data-form-style-bg="1" data-form-style-bg-content="1" data-form-style-bg-block="1" data-form-style-header-font-size="1" data-form-style-main-font-weight="1" data-form-style-button-font-color="1" data-form-style-border-block="1">
			</div>
			<div class="g-bg-primary g-color-primary g-brd-primary" data-form-style-main-bg="1" data-form-style-main-border-color="1" data-form-style-main-font-color-hover="1">
			</div>
			<div class="g-bg-gray-light-v5 g-color-gray-dark-v1 g-brd-around g-brd-white rounded-0" data-form-style-input-bg="1" data-form-style-input-select-bg="1" data-form-style-input-border="1" data-form-style-input-border-radius="1" data-form-style-main-font-color="1">
			</div>
			<div class="g-brd-around g-brd-gray-light-v2 g-color-gray-dark-v5 g-bg-black-opacity-0_7" data-form-style-input-border-color="1" data-form-style-input-border-hover="1" data-form-style-icon-font-color="1">
			</div>


			<!--			for resource booking-->
			<div class="g-bg-gray-dark-v5" data-form-style-bg-as-text="1">
			</div>

			<div class="g-bg-gray-light-v5" data-form-style-input-bg-light="1">
			</div>

			<div class="g-bg-gray-light-v4" data-form-style-input-bg-light2="1">
			</div>

			<div class="g-bg-primary-opacity-0_4" data-form-style-main-bg-light="1">
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 order-2 order-md-1">
				<div class="bitrix24forms g-brd-white-opacity-0_6 u-form-alert-v4" data-b24form="37|bvr7kg" data-b24form-use-style="Y" data-b24form-show-header="N" data-b24form-original-domain="https://movens.bitrix24.ru"></div>
			</div>

			<div class="col-md-6 order-1 order-md-2">
				<div class="text-center g-overflow-hidden">
					<h3 class="landing-block-node-main-title h3 text-uppercase g-font-weight-700 g-color-black text-left g-mb-10 g-font-size-20">'.$vars['block_7_header'].'</h3>

					<div class="landing-block-node-text g-line-height-1_5 text-left g-mb-40 g-color-gray-dark-v5" data-form-style-main-font-family="1" data-form-style-main-font-weight="1" data-form-style-header-text-font-size="1"><p>'.$vars['block_7_text'].'</p></div>
					<div class="g-mx-minus-2 g-my-minus-2">
						<div class="row mx-0"><div class="landing-block-card-contact js-animation fadeIn col-sm-6 g-brd-left g-brd-bottom g-brd-gray-light-v4 g-px-15 g-py-25 landing-card" data-card-preset="link" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
								<a href="tel:+74954142242" class="landing-block-card-linkcontact-link g-text-decoration-none--hover" target="_self">
									<span class="landing-block-card-contact-icon-container g-color-primary g-line-height-1 d-inline-block g-font-size-50 g-mb-30">
										<i class="landing-block-card-linkcontact-icon icon-call-in" data-pseudo-url="{&quot;text&quot;:&quot;&quot;,&quot;href&quot;:&quot;&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;enabled&quot;:false}"></i>
									</span>
									<span class="landing-block-card-linkcontact-title h3 d-block text-uppercase g-font-size-11 g-color-gray-dark-v5 mb-0" data-form-style-label-font-weight="1" data-form-style-label-font-size="1" data-form-style-second-font-color="1">Телефон</span>
									<span class="landing-block-card-linkcontact-text g-text-decoration-none g-text-underline--hover g-font-weight-700 g-color-gray-dark-v1 g-font-size-15">+7 495 414 22 42 доб. 103</span>
								</a>
							</div><div class="landing-block-card-contact js-animation fadeIn col-sm-6 g-brd-left g-brd-bottom g-brd-gray-light-v4 g-px-15 g-py-25 landing-card" data-card-preset="link" style="animation-duration: 1000ms; animation-play-state: running; animation-name: none;">
								<a href="mailto:tickets@movens.ru" class="landing-block-card-linkcontact-link g-text-decoration-none--hover" target="_self">
									<span class="landing-block-card-contact-icon-container g-color-primary g-line-height-1 d-inline-block g-font-size-50 g-mb-30">
										<i class="landing-block-card-linkcontact-icon icon-line icon-envelope-letter" data-pseudo-url="{&quot;text&quot;:&quot;&quot;,&quot;href&quot;:&quot;&quot;,&quot;target&quot;:&quot;_self&quot;,&quot;enabled&quot;:false}"></i>
									</span>
									<span class="landing-block-card-linkcontact-title h3 d-block text-uppercase g-font-size-11 g-color-gray-dark-v5 mb-0" data-form-style-label-font-weight="1" data-form-style-label-font-size="1" data-form-style-second-font-color="1">Почта</span>
									<span class="landing-block-card-linkcontact-text g-text-decoration-none g-text-underline--hover g-font-weight-700 g-color-gray-dark-v1 g-font-size-15">tickets@movens.ru</span>
								</a>
							</div></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
        ';





?>